"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as abc
from google.protobuf import descriptor as descriptor
from google.protobuf import message as message
from google.protobuf.internal import containers as containers
from google.protobuf.internal import enum_type_wrapper as enum_type_wrapper
import builtins as builtins
import sys
import typing as typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: descriptor.FileDescriptor


_CurrencyValues: _CurrencyValues

class _CurrencyValues:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015


_CurrencyValuesEnumTypeWrapper: _CurrencyValuesEnumTypeWrapper

class _CurrencyValuesEnumTypeWrapper(enum_type_wrapper.EnumTypeWrapper[_CurrencyValues.ValueType], builtins.type):
    DESCRIPTOR: descriptor.EnumDescriptor
    UNSPECIFIED: _CurrencyValues.ValueType  # 0
    RUB: _CurrencyValues.ValueType  # 1
    USD: _CurrencyValues.ValueType  # 2
    EUR: _CurrencyValues.ValueType  # 3
    KZT: _CurrencyValues.ValueType  # 4


CurrencyValues: CurrencyValues

class CurrencyValues(_CurrencyValues, metaclass=_CurrencyValuesEnumTypeWrapper): ...

UNSPECIFIED: CurrencyValues.ValueType  # 0
RUB: CurrencyValues.ValueType  # 1
USD: CurrencyValues.ValueType  # 2
EUR: CurrencyValues.ValueType  # 3
KZT: CurrencyValues.ValueType  # 4

@typing.final

CurrencyResponse: CurrencyResponse

class CurrencyResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    ALLCURRENCIES_FIELD_NUMBER: builtins.int
    @builtins.property
    def allCurrencies(self) -> containers.RepeatedCompositeFieldContainer[Currency]: ...
    def __init__(
        self,
        *,
        allCurrencies: abc.Iterable[Currency] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["allCurrencies", b"allCurrencies"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

@typing.final

Currency: Currency

class Currency(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    CURRENCY_FIELD_NUMBER: builtins.int
    CURRENCYRATE_FIELD_NUMBER: builtins.int
    currency: CurrencyValues.ValueType
    currencyRate: builtins.float
    def __init__(
        self,
        *,
        currency: CurrencyValues.ValueType | None = ...,
        currencyRate: builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["_currency", b"_currency", "_currencyRate", b"_currencyRate", "currency", b"currency", "currencyRate", b"currencyRate"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["_currency", b"_currency", "_currencyRate", b"_currencyRate", "currency", b"currency", "currencyRate", b"currencyRate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__currency: _TypeAlias = typing.Literal["currency"]  # noqa: Y015
    _WhichOneofArgType__currency: _TypeAlias = typing.Literal["_currency", b"_currency"]  # noqa: Y015
    _WhichOneofReturnType__currencyRate: _TypeAlias = typing.Literal["currencyRate"]  # noqa: Y015
    _WhichOneofArgType__currencyRate: _TypeAlias = typing.Literal["_currencyRate", b"_currencyRate"]  # noqa: Y015
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__currency) -> _WhichOneofReturnType__currency | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__currencyRate) -> _WhichOneofReturnType__currencyRate | None: ...

@typing.final

CalculateRequest: CalculateRequest

class CalculateRequest(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    SPENDCURRENCY_FIELD_NUMBER: builtins.int
    DESIREDCURRENCY_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    spendCurrency: CurrencyValues.ValueType
    desiredCurrency: CurrencyValues.ValueType
    amount: builtins.float
    def __init__(
        self,
        *,
        spendCurrency: CurrencyValues.ValueType | None = ...,
        desiredCurrency: CurrencyValues.ValueType | None = ...,
        amount: builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["_amount", b"_amount", "_desiredCurrency", b"_desiredCurrency", "_spendCurrency", b"_spendCurrency", "amount", b"amount", "desiredCurrency", b"desiredCurrency", "spendCurrency", b"spendCurrency"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["_amount", b"_amount", "_desiredCurrency", b"_desiredCurrency", "_spendCurrency", b"_spendCurrency", "amount", b"amount", "desiredCurrency", b"desiredCurrency", "spendCurrency", b"spendCurrency"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__amount: _TypeAlias = typing.Literal["amount"]  # noqa: Y015
    _WhichOneofArgType__amount: _TypeAlias = typing.Literal["_amount", b"_amount"]  # noqa: Y015
    _WhichOneofReturnType__desiredCurrency: _TypeAlias = typing.Literal["desiredCurrency"]  # noqa: Y015
    _WhichOneofArgType__desiredCurrency: _TypeAlias = typing.Literal["_desiredCurrency", b"_desiredCurrency"]  # noqa: Y015
    _WhichOneofReturnType__spendCurrency: _TypeAlias = typing.Literal["spendCurrency"]  # noqa: Y015
    _WhichOneofArgType__spendCurrency: _TypeAlias = typing.Literal["_spendCurrency", b"_spendCurrency"]  # noqa: Y015
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__amount) -> _WhichOneofReturnType__amount | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__desiredCurrency) -> _WhichOneofReturnType__desiredCurrency | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__spendCurrency) -> _WhichOneofReturnType__spendCurrency | None: ...

@typing.final

CalculateResponse: CalculateResponse

class CalculateResponse(message.Message):
    DESCRIPTOR: descriptor.Descriptor

    CALCULATEDAMOUNT_FIELD_NUMBER: builtins.int
    calculatedAmount: builtins.float
    def __init__(
        self,
        *,
        calculatedAmount: builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = typing.Literal["_calculatedAmount", b"_calculatedAmount", "calculatedAmount", b"calculatedAmount"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = typing.Literal["_calculatedAmount", b"_calculatedAmount", "calculatedAmount", b"calculatedAmount"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__calculatedAmount: _TypeAlias = typing.Literal["calculatedAmount"]  # noqa: Y015
    _WhichOneofArgType__calculatedAmount: _TypeAlias = typing.Literal["_calculatedAmount", b"_calculatedAmount"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__calculatedAmount) -> _WhichOneofReturnType__calculatedAmount | None: ...
